name: Quality Control

on:
  pull_request:
    branches: ['*']

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v7

      - name: 'Create dummy .env file'
        run: cp .env.example .env
        shell: bash

      - uses: pnpm/action-setup@v6
        with:
          version: 11.11.0
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm check
      - run: pnpm format:check
