name: Quality Control

on:
  pull_request:
    branches: ['*']

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        command:
          - lint
          - check
          - format:check

    steps:
      - uses: actions/checkout@v7

      - name: Create dummy .env file
        run: cp .env.example .env

      - uses: pnpm/action-setup@v6
        with:
          version: 11.14.0
          run_install: false

      - uses: actions/setup-node@v7.0.0
        with:
          node-version: 24.x
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm ${{ matrix.command }}
